-- Demo-only upgrade. Run once on databases that already have demo_trade_analytics.
-- The main trade_analytics table is intentionally unchanged.
ALTER TABLE `demo_trade_analytics`
    ADD COLUMN `account_ref` VARCHAR(60) NOT NULL DEFAULT '' AFTER `ticket`,
    ADD COLUMN `signal_type` VARCHAR(30) NOT NULL DEFAULT '' AFTER `action`,
    ADD COLUMN `timeframe` VARCHAR(10) NOT NULL DEFAULT '' AFTER `signal_type`,
    ADD COLUMN `entry_time` DATETIME NULL AFTER `timeframe`,
    ADD COLUMN `exit_time` DATETIME NULL AFTER `entry_time`,
    ADD COLUMN `duration_seconds` INT NOT NULL DEFAULT 0 AFTER `exit_time`,
    ADD COLUMN `volume` DOUBLE NOT NULL DEFAULT 0 AFTER `exit_price`,
    ADD COLUMN `initial_sl` DOUBLE NOT NULL DEFAULT 0 AFTER `volume`,
    ADD COLUMN `initial_tp` DOUBLE NOT NULL DEFAULT 0 AFTER `initial_sl`,
    ADD COLUMN `commission` DOUBLE NOT NULL DEFAULT 0 AFTER `profit`,
    ADD COLUMN `swap` DOUBLE NOT NULL DEFAULT 0 AFTER `commission`,
    ADD COLUMN `net_profit` DOUBLE NOT NULL DEFAULT 0 AFTER `swap`,
    ADD COLUMN `spread_points` DOUBLE NOT NULL DEFAULT 0 AFTER `mae`,
    ADD COLUMN `atr` DOUBLE NOT NULL DEFAULT 0 AFTER `spread_points`,
    ADD COLUMN `market_regime` VARCHAR(20) NOT NULL DEFAULT '' AFTER `atr`,
    ADD COLUMN `session_name` VARCHAR(20) NOT NULL DEFAULT '' AFTER `market_regime`,
    ADD COLUMN `entry_hour` INT NOT NULL DEFAULT 0 AFTER `session_name`,
    ADD COLUMN `loss_streak_before` INT NOT NULL DEFAULT 0 AFTER `entry_hour`,
    ADD COLUMN `exit_reason` VARCHAR(40) NOT NULL DEFAULT '' AFTER `loss_streak_before`,
    ADD COLUMN `ea_version` VARCHAR(20) NOT NULL DEFAULT '' AFTER `exit_reason`,
    ADD COLUMN `settings_hash` VARCHAR(100) NOT NULL DEFAULT '' AFTER `ea_version`,
    ADD COLUMN `level_price` DOUBLE NOT NULL DEFAULT 0 AFTER `settings_hash`,
    ADD COLUMN `pivot_time` DATETIME NULL AFTER `level_price`,
    ADD COLUMN `result` VARCHAR(20) NOT NULL DEFAULT '' AFTER `pivot_time`,
    ADD COLUMN `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `created_at`,
    ADD INDEX `idx_demo_trade_exit_time` (`exit_time`),
    ADD INDEX `idx_demo_trade_result` (`result`),
    ADD INDEX `idx_demo_trade_signal_type` (`signal_type`);
